### PR TITLE
Junit test

### LINKED ISSUE #16: Android CashSDK Release 1.4
Changes:
- Fix issue were the `CashSDK` was showing valid session when the session was not created due to an http error. https://github.com/atmcoin/cash-sdk-android/pull/14
- Fixed the issue where the AtmList by location was not working because the params were inverted. https://github.com/atmcoin/cash-sdk-android/pull/13
- Initial UnitTest coverage by @anasoid https://github.com/atmcoin/cash-sdk-android/pull/12

### PR DESCRIPTION
**Pull request by anasoid**
https://github.com/atmcoin/cash-sdk-android/issues/11

### CODE REVIEW

File: CashSDK/src/test/java/cash/just/sdk/AtmApiLoginTest.kt [hunk 1]
```diff
@@ -38,30 +41,33 @@ class AtmApiLoginTest() : AbstractAtmApiTest() {
...
+                countDownResponse.countDown();
             }
 
             override fun onError(errorMessage: String?) {
                 error = "error :" + errorMessage
+                countDownResponse.countDown();
             }
         })
-        Thread.sleep(500)
+        countDownResponse.await(500,TimeUnit.MILLISECONDS)
```
Comment (dabitdev) [inline CashSDK/src/test/java/cash/just/sdk/AtmApiLoginTest.kt:56]: do you need the time here?

File: CashSDK/src/test/java/cash/just/sdk/AtmApiLoginTest.kt [hunk 2]
```diff
@@ -38,30 +41,33 @@ class AtmApiLoginTest() : AbstractAtmApiTest() {
         val server = Cash.BtcNetwork.TEST_LOCAL
         var sessionKeyCreated: String = "";
         var error: String = "";
-
+        val countDownResponse : CountDownLatch = CountDownLatch(1)
         CashSDK.createSession(server, object : Cash.SessionCallback {
             override fun onSessionCreated(sessionKey: String) {
                 sessionKeyCreated = sessionKey;
+                countDownResponse.countDown();
```
Comment (dabitdev) [inline CashSDK/src/test/java/cash/just/sdk/AtmApiLoginTest.kt:48]: You might like to create a function for `CashSDK.createSession` to do not repeat this block in each test.
You might use @Before and start the tests always with a valid session.

Comment (anasoid) [reply CashSDK/src/test/java/cash/just/sdk/AtmApiLoginTest.kt:48]: function is already created in class AbstractAtmApiTest.

AtmApiLoginTest.kt  is to test login this is way many login call can done with different case
